# Generated by Django 3.1.6 on 2021-02-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0001_initial'),
        ('event', '0002_auto_20210226_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=58)),
                ('why', models.CharField(max_length=58)),
                ('what', models.CharField(max_length=58)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speaker.speaker')),
            ],
        ),
        migrations.DeleteModel(
            name='EventSpeaker',
        ),
    ]
