# Generated by Django 3.1.6 on 2021-02-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210226_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='episode',
            field=models.IntegerField(unique=True),
        ),
    ]
