# Generated by Django 3.1.6 on 2021-02-26 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210226_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='poster/event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='poster/speaker'),
            preserve_default=False,
        ),
    ]
