# Generated by Django 3.1.6 on 2021-02-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=29)),
                ('position', models.CharField(max_length=323)),
                ('avatar', models.ImageField(upload_to='speakers')),
            ],
        ),
    ]
